[package]
name = "rust-block-iter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.29"
bitcoincore-rpc = "0.17.0"
rawtx-rs = { version="0.1.3", features = [ "counterparty" ] }

